### ISSUE TITLE
multi-GPU implementation

### ISSUE THREAD

**Issue by moonlioght** [yd-kwon/MatNet#11]
In your paper, you mentioned that for n=50/100 large scale data, you adopted a multi-GPU implementation, I wonder if it is possible to provide a multi-GPU version of the code

**Comment by yd-kwon** [comment]
Hi. We used torch.multiprocessing and mp.Queue. 
Basically, each gpu processes smaller batch, calculates "grad"s of all parameters of the neural net model, and sends them (via Queue) to one gpu. "grad"s are accumulated, so that we can update the global model. At the time, we did it manually, but I am sure there are many different libraries available that makes such distributed GPU computing much much easier. 
Unfortunately, we are not allowed to share our old multi-gpu code at this moment. Good luck, and thanks for your interest.
